name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 8 * * 1" # every Monday at 8am

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1.7.0
      with:
        install-uv: true
        install-just: true

    - uses: actions/create-github-app-token@v3.2.0
      id: generate-token
      with:
        app-id: ${{ vars.CREATE_PR_APP_ID }}
        private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}

    - uses: bennettoxford/update-dependencies-action@v1
      with:
        token: ${{ steps.generate-token.outputs.token }}
